name: Update rules, convert, and publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - list_rules.txt
      - json_rules.txt
      - .github/workflows/update.yml

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Ensure directories exist
        run: |
          mkdir -p list json srs

      - name: Clean list/, json/, srs/
        shell: bash
        run: |
          set -euo pipefail
          for d in list json srs; do
            mkdir -p "$d"
            find "$d" -mindepth 1 -exec rm -rf {} +
          done

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Build sing-rules-converter from source
        run: |
          git clone https://github.com/solanab/sing-rules-converter.git
          cd sing-rules-converter
          go build
          mv sing-rules-converter $HOME/go/bin/
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Download .list files from list_rules.txt
        shell: bash
        run: |
          set -euo pipefail
          while IFS= read -r url || [[ -n "$url" ]]; do
            [[ -z "${url// }" || "${url}" =~ ^[[:space:]]*# ]] && continue
            clean="${url%%\?*}"
            base="$(basename "$clean")"
            [[ "$base" != *.list ]] && base="${base}.list"
            echo "Fetching: $url -> list/$base"
            curl -fsSL "$url" -o "list/$base"
          done < list_rules.txt

      - name: Convert .list -> .json/.srs
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in list/*.list; do
            echo "Converting $f"
            sing-rules-converter "$f"
          done

      - name: Move generated files into json/ and srs/
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in list/*.json; do mv -f "$f" json/; done
          for f in list/*.srs; do mv -f "$f" srs/; done

      # ===== JSON-specific bits below (minimal additions) =====

      - name: Install sing-box
        shell: bash
        run: |
          set -euo pipefail
          sudo mkdir -p /etc/apt/keyrings
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo '
          Types: deb
          URIs: https://deb.sagernet.org/
          Suites: *
          Components: *
          Enabled: yes
          Signed-By: /etc/apt/keyrings/sagernet.asc
          ' | sudo tee /etc/apt/sources.list.d/sagernet.sources
          sudo apt-get update
          sudo apt-get install -y sing-box

      - name: Download .json files from json_rules.txt
        shell: bash
        run: |
          set -euo pipefail
          rules="json_rules.txt"
          if [[ -s "$rules" ]]; then
            echo "Using rules file: $rules"
            while IFS= read -r url || [[ -n "$url" ]]; do
              [[ -z "${url// }" || "${url}" =~ ^[[:space:]]*# ]] && continue
              clean="${url%%\?*}"
              base="$(basename "$clean")"
              [[ "$base" != *.json ]] && base="${base}.json"
              echo "Fetching: $url -> json/$base"
              curl -fsSL "$url" -o "json/$base"
            done < "$rules"
          else
            echo "json_rules.txt missing or empty; skipping JSON downloads."
          fi


      - name: Compile json/*.json -> srs/*.srs with sing-box
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in json/*.json; do
            base="$(basename "${f%.json}")"
            out="srs/${base}.srs"
            echo "Compiling $f -> $out"
            sing-box rule-set compile --output "$out" "$f"
          done

      # ===== end of JSON-specific additions =====

      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add list json srs || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: clean, update rules, and regenerate"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
